name: Run Bando Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11,21 * * *'  # Twice daily (UTC 11:00 and 21:00)

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4 playwright playwright-stealth
        playwright install chromium

    - name: Run monitor script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: python monitor.py
